import subprocess

# List of titles
titles = [
"Little Fires Everywhere",
"Hollywood",
"Into the Night",
"Perry Mason",
"Killer Inside: The Mind of Aaron Hernandez (2020)",
"Brave New World (2020)",
"Good Omens",
"For All Mankind",
"Spartacus: Gods of the Arena",
"The Pacific",
"The Fall of the House of Usher",
"Black Bird",
"Dexter: New Blood",
"Maniac",
"Godless",
"Defending Jacob",
"Clickbait",
"Generation Kill",
"Safe 2018",
"And Then There Were None",
"The Act",
"Alias Grace",
"John Adams",
"Love & Death",
"Servant",
"The Righteous Gemstones",
"How to Sell Drugs Online (Fast)",
"Conversations with a Killer: The Ted Bundy Tapes",
"Firefly",
"Fresh Off the Boat",
"You're the Worst",
"Kidding",
"Brockmire",
"Miracle Workers",
"Fresh Off the Boat",
"Brockmire",
"trese",
"Castlevania: Nocturne",
"Captain Laserhawk: A Blood Dragon Remix",
"pantheon",
"Dirty Money",
"Icarus (2017)",
"Ugly Delicious",
"Fed Up (2014)",
"Evil Genius: The True Story of America's Most Diabolical Bank Heist",
"The Gentlemen",
"3 Body Problem",
"Shōgun",
"silo",
"The Fall of the House of Usher",
"gen V",
"Shrinking",
"Blue Eye Samurai",
"Sapne Vs Everyone",
"The Diplomat",
"Chamak",
"Poker Face",
"Jury Duty",
"silo",
"All the Light We Cannot See",
"Love & Death",
"beckham",
"Lessons in Chemistry",
"The Crowded Room",
"Painkiller",
"Dear Child",
"Twisted Metal",
"A Murder at the End of the World",
"Arnold",
"The Railway Men",
"Rabbit Hole",
"Wednesday",
"The Sandman",
"1899",
"Black Bird",
"The Peripheral",
"Cyberpunk: Edgerunners",
"From",
"The Lincoln Lawyer",
"Archive 81",
"Vikings: Valhalla",
"Guillermo del Toro's Cabinet of Curiosities",
"1923",
"Our Flag Means Death",
"NCR Days",
"Tokyo Vice",
"The Summer I Turned Pretty",
"Pam & Tommy",
"the offer",
"The Gilded Age",
"Under the Banner of Heaven",
"Outer Range",
"the patient",
"the english",
"The Tourist",
"fallout",
" The Gentlemen",
"Ahsoka",
"Invincible",
"Only Murders in the Building",
"The Chestnut Man",
"The Innocent",
"baby reindeer",
"shogun",
"It's a Sin",
"Inside Job",
"Young Rock",
"The Undoing",

]

# Iterate over titles and run the command
for title in titles:
    command = ["python", "-m", "1337x", title]
    subprocess.run(command)

